FROM golang:1.12.1-alpine3.9 as build

RUN apk add --no-cache git curl

RUN mkdir -p /go/src/app
WORKDIR /go/src/app

RUN go get github.com/streadway/amqp
RUN go get log
RUN go get time
RUN go get encoding/json
RUN go get flag
RUN go get github.com/gin-gonic/gin
RUN go get io/ioutil
RUN go get os
RUN go get sync


COPY ./src /go/src/app/

RUN go build -o app
################################################################################################################

FROM alpine:3.9

RUN mkdir -p /app
COPY --from=build /go/src/app/app /app/
WORKDIR /app

CMD ["./app"]